apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcpsm-secret-store
  namespace: autonova
spec:
  provider:
    gcpsm:
      projectID: "YOUR_GCP_PROJECT_ID"  # Replace with your GCP project ID
      auth:
        workloadIdentity:
          clusterLocation: us-central1
          clusterName: autonova-cluster
          serviceAccountRef:
            name: external-secrets
