apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-booking-service
  labels:
    app: appointment-booking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-booking-service
  template:
    metadata:
      labels:
        app: appointment-booking-service
    spec:
      containers:
        - name: appointment-booking-service
          image: jalinahirushan02/appointment-booking-service:dev-latest
          ports:
            - containerPort: 8088
          envFrom:
            - secretRef:
                name: autonova-env
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8088
            initialDelaySeconds: 60
            periodSeconds: 30
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
