apiVersion: v1
kind: Service
metadata:
  name: appointment-booking-service
  labels:
    app: appointment-booking-service
spec:
  selector:
    app: appointment-booking-service
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
  type: ClusterIP
