apiVersion: v1
kind: Service
metadata:
  name: chatbot
  labels:
    app: chatbot
    monitoring: enabled
spec:
  selector:
    app: chatbot
  ports:
    - port: 8097
      targetPort: 8097
      name: http
  type: ClusterIP
