apiVersion: v1
kind: Service
metadata:
  name: chatbot
  labels:
    app: chatbot
spec:
  selector:
    app: chatbot
  ports:
    - protocol: TCP
      port: 8097
      targetPort: 8097
  type: ClusterIP
