apiVersion: apps/v1
kind: Deployment
metadata:
  name: progress-monitoring
  labels:
    app: progress-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: progress-monitoring
  template:
    metadata:
      labels:
        app: progress-monitoring
    spec:
      containers:
        - name: progress-monitoring
          image: jalinahirushan02/progress-monitoring-service:dev-latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: autonova-env
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            requests:
              cpu: "120m"
              memory: "160Mi"
