apiVersion: v1
kind: Service
metadata:
  name: progress-monitoring
  labels:
    app: progress-monitoring
spec:
  type: ClusterIP
  selector:
    app: progress-monitoring
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
