apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-logging-service
  labels:
    app: time-logging-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: time-logging-service
  template:
    metadata:
      labels:
        app: time-logging-service
    spec:
      containers:
        - name: time-logging-service
          image: jalinahirushan02/time-logging-service:dev-latest
          ports:
            - containerPort: 8083
          env:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: autonova-env
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: autonova-env
                  key: POSTGRES_PORT
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: autonova-env
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: autonova-env
                  key: TIME_LOGGING_DB_PASSWORD
            - name: PGDATABASE
              value: "time_logging_db"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 30
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
