apiVersion: v1
kind: Service
metadata:
  name: payments-billing-service
  labels:
    app: payments-billing-service
spec:
  type: ClusterIP
  selector:
    app: payments-billing-service
  ports:
    - port: 8069
      targetPort: 8069
      protocol: TCP
      name: http
