spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:ep-mute-thunder-adhoybp1-pooler.c-2.us-east-1.aws.neon.tech}:${DB_PORT:5432}/${DB_NAME:appointment_db}?sslmode=require
    username: ${DB_USERNAME:appointment_service}
    password: ${DB_PASSWORD:appointment_db_password}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    # Recommended for non-prod/dev only: let Hibernate create/update schema from entities
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: never   # set to 'always' if using schema.sql and you want Spring to run it
#  security:
#    oauth2:
#          resourceserver:
#            jwt:
#              jwk-set-uri: https://auth-server.example.com/.well-known/jwks.json

server:
  port: 8088

# security jwt jwk-set-uri example (resource-server)

# Logging
logging:
  level:
    org.hibernate.SQL: DEBUG
